typography_spectrum: 0.2921896668880403
color:
  brandStrength: 0.3265962691367189
  lightness: 0.9338477892429559
  saturation: 0.17135510252087868
  rhythmicContrast: 0.5536037222108814
  brandColors:
    - '#FFFFFF'
    - '#241F20'
    - '#FFD04B'
    - '#5F5F5F'
    - '#C7C7C7'
github: true
layout_spectrum: 0.14920425847836652
author:
  name: Barry Scheurweghs
  email: surewaytolive@gmail.com
  url: SurewayFinancial.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/c301349b-1f65-4874-abd2-9f65106e821b.png
name: Financial Consultants
url: 'http://surewayfinancial.com'
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/28c92b2f-acf6-4a39-8210-d81a5e04fb5d.jpg
title: Sureway Financial
content: []
description: We're Hiring Financial Consultants
purpose:
  - type: contact
    url: 'tel:480-360-1864'
    label: TEXT/CALL
  - type: external
    url: 'https://calendly.com/surewaytolive/15min/12-31-2016?back=1'
    label: SCHEDULE INTERVIEW
