typography_spectrum: 0.5130936359722942
content_rating:
  adult: false
color:
  brandColors:
    - '#85DB18'
    - '#CDE855'
    - '#F5F6D4'
    - '#A7C520'
    - '#493F0B'
  brandStrength: 0.7008417538016812
  lightness: 0.863211317706097
  saturation: 0.09436048940202166
  rhythmicContrast: 0.3912586180715462
github: true
opengraph:
  type: ''
  appId: ''
layout_spectrum: 0.3072374792451426
author:
  name: Barry Scheurweghs
  url: 'http://surewayfinancial.com'
  email: surewaytolive@gmail.com
logo: null
name: Sureway Financial
favicon: null
title: Sureway Financial
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: video
    html: >-
      <iframe
      src="https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2FMV8AUTd6C8U%3Ffeature%3Doembed&url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DMV8AUTd6C8U&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2FMV8AUTd6C8U%2Fhqdefault.jpg&key=b7d04c9b404c499eba89ee7072e1c4f7&type=text%2Fhtml&schema=youtube"
      width="640" height="360" scrolling="no" frameborder="0"
      allowfullscreen></iframe>
    src: !<tag:yaml.org,2002:js/undefined> ''
    metadata:
      author:
        - name: Symmetry Financial Group
          url: 'https://www.youtube.com/channel/UCM2fbnSc9kUsuKTC1qwseLg'
          avatar: {}
      related: []
      publisher:
        url: 'https://www.youtube.com/'
        name: YouTube
        favicon: 'https://s.ytimg.com/yts/img/favicon-vflz7uhzw.ico'
        domain: youtu.be
      keywords:
        - symmetry
        - duration
        - views
        - financial
        - overview
        - group
        - corporate
        - sfg
        - interview
        - chadwick
      description: Uploaded by Symmetry Financial Group on 2015-03-20.
      inLanguage: en
      '@type': VideoObject
      app_links:
        - url: 'vnd.youtube://www.youtube.com/watch?v=MV8AUTd6C8U&feature=applinks'
          type: ios
          namespace: ai
          app_store_id: '544007664'
          app_name: YouTube
        - url: 'vnd.youtube://www.youtube.com/watch?v=MV8AUTd6C8U&feature=applinks'
          type: android
          namespace: ai
          app_name: YouTube
          package: com.google.android.youtube
        - url: 'https://www.youtube.com/watch?v=MV8AUTd6C8U&feature=applinks'
          type: web
          namespace: ai
        - url: 'vnd.youtube://www.youtube.com/watch?v=MV8AUTd6C8U&feature=applinks'
          namespace: twitter
          type: ipad
          name: YouTube
          id: '544007664'
        - url: 'vnd.youtube://www.youtube.com/watch?v=MV8AUTd6C8U&feature=applinks'
          namespace: twitter
          type: iphone
          name: YouTube
          id: '544007664'
        - url: 'https://www.youtube.com/watch?v=MV8AUTd6C8U'
          namespace: twitter
          type: googleplay
          name: YouTube
          id: com.google.android.youtube
        - path: http/www.youtube.com/watch?v=MV8AUTd6C8U
          package: com.google.android.youtube
          namespace: google
          type: android
        - path: vnd.youtube/www.youtube.com/watch?v=MV8AUTd6C8U
          package: '544007664'
          namespace: google
          type: ios
      '@context': 'http://schema.org'
      isBasedOnUrl: 'https://youtu.be/MV8AUTd6C8U'
      title: Symmetry Financial Group Corporate Overview
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: Hiring and Training FT/PT Insurance Agents
purpose:
  - type: external
    url: 'https://calendly.com/surewaytolive/15min/01-21-2017?back=1'
    label: Schedule A Call
analytics:
  google: google847b49e679f646db.html
