layout_spectrum: 0.042755995030690094
typography_spectrum: 0.6910392131067185
color:
  brandStrength: 0.39406371701813053
  lightness: 0.18147583654224134
  saturation: 0.3908922377900949
  rhythmicContrast: 0.7140456862073613
  brandColors:
    - '#1C1D21'
    - '#31353D'
    - '#445878'
    - '#92CDCF'
    - '#EEEFF7'
github: true
author:
  name: Barry Scheurweghs
  email: surewaytolive@gmail.com
  url: 'http://surewayfinancial.com'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/c301349b-1f65-4874-abd2-9f65106e821b.png
name: Financial Consultants
url: 'http://surewayfinancial.com'
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/28c92b2f-acf6-4a39-8210-d81a5e04fb5d.jpg
title: Sureway Financial is Hiring Financial Consultants
content: []
description: Schedule Your Interview
purpose:
  - type: external
    url: 'https://calendly.com/surewaytolive/15min/12-31-2016?back=1'
    label: SCHEDULE INTERVIEW
