layout_spectrum: 0.8072388473787521
typography_spectrum: 0.11493370444919582
color:
  brandStrength: 0.20372075509639587
  lightness: 0.6143939002559031
  saturation: 0.3618780537429127
  rhythmicContrast: 0.051896046892749056
  brandColors:
    - '#E6E2AF'
    - '#A7A37E'
    - '#EFECCA'
    - '#046380'
    - '#002F2F'
github: true
author:
  name: Barry Scheurweghs
  email: surewaytolive@gmail.com
  url: 'http://surewayfinancial.com'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/c301349b-1f65-4874-abd2-9f65106e821b.png
name: Financial Consultants
url: 'http://surewayfinancial.com'
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/28c92b2f-acf6-4a39-8210-d81a5e04fb5d.jpg
title: Sureway Financial is Hiring Financial Consultants
content: []
description: Schedule Your Interview
purpose:
  - type: external
    url: 'https://calendly.com/surewaytolive/15min/12-31-2016?back=1'
    label: SCHEDULE INTERVIEW
