typography_spectrum: 0.5130936359722942
content_rating:
  adult: false
color:
  brandColors:
    - '#85DB18'
    - '#CDE855'
    - '#F5F6D4'
    - '#A7C520'
    - '#493F0B'
  brandStrength: 0.7008417538016812
  lightness: 0.863211317706097
  saturation: 0.09436048940202166
  rhythmicContrast: 0.3912586180715462
github: true
opengraph:
  type: ''
  appId: ''
layout_spectrum: 0.3072374792451426
author:
  name: Barry Scheurweghs
  url: 'http://surewayfinancial.com'
  email: surewaytolive@gmail.com
logo: null
name: Sureway Financial
favicon: null
title: Sureway Financial
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://s3-us-west-2.amazonaws.com/the-grid-img/p/1f97b5c5c72b9cfd3a72d36ad25cc7bf697a4543.jpg">
    src: >-
      https://s3-us-west-2.amazonaws.com/the-grid-img/p/1f97b5c5c72b9cfd3a72d36ad25cc7bf697a4543.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://s3-us-west-2.amazonaws.com'
        name: .s3-us-west-2.amazonaws.com
        favicon: null
        domain: imgflo.herokuapp.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      isBasedOnUrl: >-
        https://imgflo.herokuapp.com/graph/2b2431f8e7ba7b0/55f621592769dbb9f42792c68b2e3ba0/noop.jpg?input=https%3A%2F%2Fimg.youtube.com%2Fvi%2FMV8AUTd6C8U%2Fmaxresdefault.jpg
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/de75bd6f-1233-4a55-83e3-113e32afd94d.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/de75bd6f-1233-4a55-83e3-113e32afd94d.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: Hiring and Training FT/PT Insurance Agents
purpose:
  - type: external
    url: 'https://calendly.com/surewaytolive'
    label: Schedule Interview
