typography_spectrum: 0.5130936359722942
content_rating:
  adult: false
color:
  brandColors:
    - '#85DB18'
    - '#CDE855'
    - '#F5F6D4'
    - '#A7C520'
    - '#493F0B'
  brandStrength: 0.7008417538016812
  lightness: 0.863211317706097
  saturation: 0.09436048940202166
  rhythmicContrast: 0.3912586180715462
github: true
opengraph:
  type: ''
  appId: ''
layout_spectrum: 0.3072374792451426
author:
  name: Barry Scheurweghs
  url: 'http://surewayfinancial.com'
  email: surewaytolive@gmail.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/c301349b-1f65-4874-abd2-9f65106e821b.png
name: Sureway Financial
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/28c92b2f-acf6-4a39-8210-d81a5e04fb5d.jpg
title: We're Hiring Consultants
content: []
description: ''
purpose:
  - type: external
    url: 'https://calendly.com/surewaytolive'
    label: Schedule Interview
