typography_spectrum: 0.5130936359722942
content_rating:
  adult: false
color:
  brandColors:
    - '#85DB18'
    - '#CDE855'
    - '#F5F6D4'
    - '#A7C520'
    - '#493F0B'
  brandStrength: 0.7008417538016812
  lightness: 0.863211317706097
  saturation: 0.09436048940202166
  rhythmicContrast: 0.3912586180715462
github: true
opengraph:
  type: ''
  appId: ''
layout_spectrum: 0.3072374792451426
author:
  name: Barry Scheurweghs
  url: 'http://surewayfinancial.com'
  email: surewaytolive@gmail.com
logo: null
name: Sureway Financial
favicon: null
title: Sureway Financial Insurance
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/115e2199-297a-4fbd-a7df-f151d7cf641f.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/115e2199-297a-4fbd-a7df-f151d7cf641f.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      inLanguage: !<tag:yaml.org,2002:js/undefined> ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: Hiring & Training FT/PT Insurance Agents
purpose:
  - type: external
    url: 'https://calendly.com/surewaytolive/15min/01-21-2017?back=1'
    label: Schedule A Call
analytics:
  google: UA-76409043-2
